### ISSUE TITLE
Usage with pug

### ISSUE THREAD

**Issue by Toilal** [ktsn/vue-template-loader#16]
Is it possible to use this loader with [pug-loader](https://github.com/pugjs/pug-loader) ? (formerly jade template engine)

**Comment by ktsn** [comment]
Yes, you can use it with pug, sass and any other preprocessors. We only need to add `rules` for each file type. (Note that you should use `pug-html-loader` to use pug with this loader)

I just add an example using such preprocessors. 
https://github.com/ktsn/vue-template-loader/tree/master/examples/complex
