### ISSUE TITLE
Can add a webpack css loader with scoped css for typescript?

### ISSUE THREAD

**Issue by yeluoqiuzhi** [ktsn/vue-template-loader#2]
Can you add a webpack css loader with scoped css for typescript?

usage like @withRenderer

**Comment by ktsn** [comment]
I actually considered that feature but it can be complicated implementation and API, so I needed to take a time to design that.
The final API may be passing css file path to loader's query (`import with Render from './app.html?style=app.css'`) or providing a separated loader (vue-scoped-style-loader?).

Do you have any other ideas?

**Comment by yeluoqiuzhi** [comment]
loader's query is enough

**Comment by sqal** [comment]
hi @ktsn what about support for css modules? Can it be solved with this loader?

**Comment by ktsn** [comment]
It probably can. I'll try to implement that after scoped css.

**Comment by ktsn** [comment]
Scoped css and CSS Modules are shipped as [v0.2.1](https://github.com/ktsn/vue-template-loader/releases/tag/v0.2.1)
