### ISSUE TITLE
Move "vue-template-compiler" to dependencies.

### ISSUE THREAD

**Issue by blieque** [ktsn/vue-template-loader#38]
Sorry if I'm missing something, but I think `vue-template-compiler` needs to be a `dependency` as well as a `devDependency`, or perhaps just the former. I ran `npm i -D vue-template-loader`, but the webpack build failed until I manually installed `vue-template-compiler` too.

**Comment by ktsn** [comment]
It is in peerDependencies.

**Comment by blieque** [comment]
I admit I missed that, but I still feel like it should be a standard dependency. `vue-template-loader` isn't a plugin for `vue-template-compiler`, but rather requires it to operate. I think `vue-template-loader` should depend on it in just the same way that `vueify` does. It seems `vue-loader` also only specifies it in `devDependencies`, which I find very odd. Is there reasoning to it? Bear in mind that NPM ^3.0.0 doesn't install `peerDependencies` by default.

**Comment by ktsn** [comment]
Because, if we add it as direct dependency, the users cannot specify vue-template-compiler version. It will occur version mismatch error with Vue core.
