### ISSUE TITLE
Does it have to have two root level dom element?

### ISSUE THREAD

**Issue by yeluoqiuzhi** [ktsn/vue-template-loader#4]
This will work.

```html
<div class="apply-home">
    <span>something</span>
</div>
```

But this doesn't work.

```html
<div class="apply-home">
  something
</div>
```

**Comment by yeluoqiuzhi** [comment]
This also not work.

Just add a class to span tag.

```html
<div class="apply-home">
    <span class="something">dkfk</span>
</div>
```

**Comment by ktsn** [comment]
I can't reproduce this. Could you share your whole code that reproduce this issue?

**Comment by yeluoqiuzhi** [comment]
There is some mistakes in my project, I can't reproduce now...

I have pushed it to [vue-ts-template](https://github.com/yeluoqiuzhi/vue-ts-template).it work well.
However I don't know how to configure karma-coverage or other thing that can report test coverage to me.

**Comment by yeluoqiuzhi** [comment]
I leave over some Chinese character in the project, will it annoy you?

**Comment by ktsn** [comment]
I never mind about that.

> However I don't know how to configure karma-coverage or other thing that can report test coverage to me

I'm sorry, I don't familiar with karma and any coverage tools...

**Comment by yeluoqiuzhi** [comment]
ok.thanks
