### ISSUE TITLE
Expose preserveWhitespace to vue-template-loader

### ISSUE THREAD

**Issue by kennardconsulting** [ktsn/vue-template-loader#44]
Thanks for all your hard work on vue-template-loader!

Would it be possible to expose the `preserveWhitespace` option as discussed here: https://github.com/vuejs/vue/issues/3934

At present my input looks like this:

```
<p>
	My gross annual salary is
</p>
```

And my output looks like this:

`_c('p',[_vm._v("\r\n\t\tMy gross annual salary is\r\n\t\t")`

I would love it to look like this:

`_c('p',[_vm._v("My gross annual salary is")`

**Comment by ktsn** [comment]
We can't add the feature which vue-template-compiler does not support.

**Comment by kennardconsulting** [comment]
Sorry for not being clear. I believe `preserveWhitespace` _is_ already supported by `vue-template-compiler`. As explained here:

https://github.com/vuejs/vue/blob/d362d64633f00f8cbf1613c424d8852fb45c7596/packages/vue-template-compiler/README.md#options

I think I just need you to expose it?

**Comment by ktsn** [comment]
We can expose the option, but `preserveWhitespace: false` does not trim text nodes but eliminate whitespace **between** elements.
https://jsfiddle.net/m5zyuvux/

**Comment by kennardconsulting** [comment]
Thanks for being so responsive!

I take your point. I understand now that this won't solve my problem. It may be useful to expose it for now anyway, and hopefully expose some other option in the future (`preserveWhitespaceWithinElements` or something).

It's actually a correctness issue, I think.
