### ISSUE TITLE
Handle ES6 default export

### ISSUE THREAD

**Issue by sqal** [ktsn/vue-template-loader#7]
I am getting this error while loading my component dynamically in route configuration:

```
[Vue warn]: Failed to mount component: template or render function not defined. 
(found in anonymous component - use the "name" option for better debugging messages.)
```

```
{
  path: '/auth',
  component: () => import('./components/Auth')
}
```

![img1](https://cloud.githubusercontent.com/assets/3576913/21648253/9f77aa9a-d29d-11e6-857e-d78670122bb3.png)

And to fix this i have to replace everywhere my imports to `import(path).then(m => m.default)`

I don't have this problem with `.vue` files because vue-loader does this thing https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L245 Can this be added to this loader as well?

**Comment by ktsn** [comment]
Unfortunately, we can't. Because this loader does not care about js files.
Also, vue-loader's behavior is not compatible with ES Module standard (I guess it's due to backward compatibility), so I personally think we should not rely on that behavior.
